/* Generated By:JJTree: Do not edit this line. ASTA.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTA extends SimpleNode {
  public ASTA(int id) {
    super(id);
  }

  public ASTA(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2caf2752505df7105db4dd880702fe54 (do not edit this line) */
