/* Generated By:JJTree: Do not edit this line. ASTAsignacion.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAsignacion extends SimpleNode {
  public ASTAsignacion(int id) {
    super(id);
  }

  public ASTAsignacion(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5f054080ffa5dbcd5d1b7507137e378c (do not edit this line) */
