/* Generated By:JJTree: Do not edit this line. ASTAsignacion.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAsignacion extends SimpleNode {
  public ASTAsignacion(int id) {
    super(id);
  }

  public ASTAsignacion(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4aaec8f01e3601eb0c5a132e3f923e7a (do not edit this line) */
