/* Generated By:JJTree: Do not edit this line. ASTBloque.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBloque extends SimpleNode {
  public ASTBloque(int id) {
    super(id);
  }

  public ASTBloque(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0a38468cb50b7321191bfebe54643b11 (do not edit this line) */
