/* Generated By:JJTree: Do not edit this line. ASTBreak.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBreak extends SimpleNode {
  public ASTBreak(int id) {
    super(id);
  }

  public ASTBreak(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3dbe7238a0e00063a175aa5cdf5d71af (do not edit this line) */
