/* Generated By:JJTree: Do not edit this line. ASTBloqueVariablesLocales.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBloqueVariablesLocales extends SimpleNode {
  public ASTBloqueVariablesLocales(int id) {
    super(id);
  }

  public ASTBloqueVariablesLocales(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4be6c0cbf93eec8202644a5820542fbf (do not edit this line) */
