/* Generated By:JJTree: Do not edit this line. ASTBloqueDeDefiniciones.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBloqueDeDefiniciones extends SimpleNode {
  public ASTBloqueDeDefiniciones(int id) {
    super(id);
  }

  public ASTBloqueDeDefiniciones(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=25648472ceeaf210a953fb8e0370eb94 (do not edit this line) */
