/* Generated By:JJTree: Do not edit this line. ASTBloqueDeDefiniciones.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBloqueDeDefiniciones extends SimpleNode {
  public ASTBloqueDeDefiniciones(int id) {
    super(id);
  }

  public ASTBloqueDeDefiniciones(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7ae0bc544bd2a1b54079f9ed978fe51d (do not edit this line) */
