/* Generated By:JJTree: Do not edit this line. ASTBloqueVariablesGlobales.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBloqueVariablesGlobales extends SimpleNode {
  public ASTBloqueVariablesGlobales(int id) {
    super(id);
  }

  public ASTBloqueVariablesGlobales(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=96d24dd671d4711aa10f06da26ec7de4 (do not edit this line) */
