/* Generated By:JJTree: Do not edit this line. ASTBloque.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBloque extends SimpleNode {
  public ASTBloque(int id) {
    super(id);
  }

  public ASTBloque(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5b7dbda7a22db3551099db19ae052178 (do not edit this line) */
