/* Generated By:JJTree: Do not edit this line. ASTBloqueVariablesGlobales.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBloqueVariablesGlobales extends SimpleNode {
  public ASTBloqueVariablesGlobales(int id) {
    super(id);
  }

  public ASTBloqueVariablesGlobales(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=131e37db79c1d902b0ef93cb55a04d05 (do not edit this line) */
