/* Generated By:JJTree: Do not edit this line. ASTComma.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTComma extends SimpleNode {
  public ASTComma(int id) {
    super(id);
  }

  public ASTComma(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a0e4e42b7b66a58ebef8636798099370 (do not edit this line) */
