/* Generated By:JJTree: Do not edit this line. ASTCARAC.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCARAC extends SimpleNode {
  public ASTCARAC(int id) {
    super(id);
  }

  public ASTCARAC(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c74188fa2d8d58a1d8718a89ea25f205 (do not edit this line) */
