/* Generated By:JJTree: Do not edit this line. ASTChr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTChr extends SimpleNode {
  public ASTChr(int id) {
    super(id);
  }

  public ASTChr(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=341bafa5bd03cf32d73d4717d288c756 (do not edit this line) */
