/* Generated By:JJTree: Do not edit this line. ASTCadena.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCadena extends SimpleNode {
  public ASTCadena(int id) {
    super(id);
  }

  public ASTCadena(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a5f2f11abf82457b66121a70b235e269 (do not edit this line) */
