/* Generated By:JJTree: Do not edit this line. ASTCARAC.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCARAC extends SimpleNode {
  public ASTCARAC(int id) {
    super(id);
  }

  public ASTCARAC(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f34f0eb24389e8cbf50c2543913cf3e7 (do not edit this line) */
