/* Generated By:JJTree: Do not edit this line. ASTComparaciones.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTComparaciones extends SimpleNode {
  public ASTComparaciones(int id) {
    super(id);
  }

  public ASTComparaciones(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a571e315222ea1b5c0ecbac9ffb58e47 (do not edit this line) */
