/* Generated By:JJTree: Do not edit this line. ASTChr.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTChr extends SimpleNode {
  public ASTChr(int id) {
    super(id);
  }

  public ASTChr(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=70ff9b5508903ced57777729b6d45e23 (do not edit this line) */
