/* Generated By:JJTree: Do not edit this line. ASTDeclaracionUnaVariable.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDeclaracionUnaVariable extends SimpleNode {
  public ASTDeclaracionUnaVariable(int id) {
    super(id);
  }

  public ASTDeclaracionUnaVariable(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5e077a91482f7d45af4be6d60e2aaabd (do not edit this line) */
