/* Generated By:JJTree: Do not edit this line. ASTDeclaracionUnaVariable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDeclaracionUnaVariable extends SimpleNode {
  public ASTDeclaracionUnaVariable(int id) {
    super(id);
  }

  public ASTDeclaracionUnaVariable(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=83a13aee546414b8cab669df8bfb6189 (do not edit this line) */
