/* Generated By:JJTree: Do not edit this line. ASTDoublePoint.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDoublePoint extends SimpleNode {
  public ASTDoublePoint(int id) {
    super(id);
  }

  public ASTDoublePoint(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ec8e81d2a5072885d079f424d304e993 (do not edit this line) */
