/* Generated By:JJTree: Do not edit this line. ASTDec.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDec extends SimpleNode {
  public ASTDec(int id) {
    super(id);
  }

  public ASTDec(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6d187812a5167bcb25b5ded5ac090b3c (do not edit this line) */
