/* Generated By:JJTree: Do not edit this line. ASTDoublePoint.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDoublePoint extends SimpleNode {
  public ASTDoublePoint(int id) {
    super(id);
  }

  public ASTDoublePoint(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7f07c5a50f1e769a2e127e7766c53bb6 (do not edit this line) */
