/* Generated By:JJTree: Do not edit this line. ASTDecimal.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDecimal extends SimpleNode {
  public ASTDecimal(int id) {
    super(id);
  }

  public ASTDecimal(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5b3538e1f2a59a5ce7ff14b6bd19dce1 (do not edit this line) */
