/* Generated By:JJTree: Do not edit this line. ASTExpresion.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpresion extends SimpleNode {
  public ASTExpresion(int id) {
    super(id);
  }

  public ASTExpresion(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b48d5e458bb68d56716e05b6b76f0ac2 (do not edit this line) */
