/* Generated By:JJTree: Do not edit this line. ASTExpresion.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpresion extends SimpleNode {
  public ASTExpresion(int id) {
    super(id);
  }

  public ASTExpresion(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=30beffc8ab0d28a05fd509f96d6282b3 (do not edit this line) */
