/* Generated By:JJTree: Do not edit this line. ASTFuncion.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFuncion extends SimpleNode {
  public ASTFuncion(int id) {
    super(id);
  }

  public ASTFuncion(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d87d66b8c83f830a0c1ed981870fc637 (do not edit this line) */
