/* Generated By:JJTree: Do not edit this line. ASTFuncion.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFuncion extends SimpleNode {
  public ASTFuncion(int id) {
    super(id);
  }

  public ASTFuncion(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=94a803a35b6234dedd1ef36aa968ef0a (do not edit this line) */
