/* Generated By:JJTree: Do not edit this line. ASTInt.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTInt extends SimpleNode {
  public ASTInt(int id) {
    super(id);
  }

  public ASTInt(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1b2ded46e703900e2816c14061ac0526 (do not edit this line) */
