/* Generated By:JJTree: Do not edit this line. ASTLparen.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLparen extends SimpleNode {
  public ASTLparen(int id) {
    super(id);
  }

  public ASTLparen(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e3e9ebf116017a4f78dac01258389c98 (do not edit this line) */
