/* Generated By:JJTree: Do not edit this line. ASTLbrace.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLbrace extends SimpleNode {
  public ASTLbrace(int id) {
    super(id);
  }

  public ASTLbrace(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6b2378a0c748ee9f8f073e39a1ff2ba0 (do not edit this line) */
