/* Generated By:JJTree: Do not edit this line. ASTLbrace.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLbrace extends SimpleNode {
  public ASTLbrace(int id) {
    super(id);
  }

  public ASTLbrace(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1640b274593583ea1cb9f8ed30ad72c5 (do not edit this line) */
