/* Generated By:JJTree: Do not edit this line. ASTOpBits.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOpBits extends SimpleNode {
  public ASTOpBits(int id) {
    super(id);
  }

  public ASTOpBits(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7a2f87dc130124a5dba6ca67eaf389cd (do not edit this line) */
