/* Generated By:JJTree: Do not edit this line. ASTOpBits.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOpBits extends SimpleNode {
  public ASTOpBits(int id) {
    super(id);
  }

  public ASTOpBits(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f2af0e7ae8bea3bcedc0b659df5f617c (do not edit this line) */
