/* Generated By:JJTree: Do not edit this line. ASTOperadores.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOperadores extends SimpleNode {
  public ASTOperadores(int id) {
    super(id);
  }

  public ASTOperadores(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=208e1efd2bcfc3c3e9eed26152778ec9 (do not edit this line) */
