/* Generated By:JJTree: Do not edit this line. ASTOperadores.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOperadores extends SimpleNode {
  public ASTOperadores(int id) {
    super(id);
  }

  public ASTOperadores(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0f7dd9a3203db5e745d0092fd8494f0c (do not edit this line) */
