/* Generated By:JJTree: Do not edit this line. ASTOpAritmetico.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOpAritmetico extends SimpleNode {
  public ASTOpAritmetico(int id) {
    super(id);
  }

  public ASTOpAritmetico(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=02ad1a5cde698cd1ebaaf2717d3658ce (do not edit this line) */
