/* Generated By:JJTree: Do not edit this line. ASTOpAritmetico.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOpAritmetico extends SimpleNode {
  public ASTOpAritmetico(int id) {
    super(id);
  }

  public ASTOpAritmetico(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=76103578294cda5112adac4b9027a678 (do not edit this line) */
