/* Generated By:JJTree: Do not edit this line. ASTPrograma.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPrograma extends SimpleNode {
  public ASTPrograma(int id) {
    super(id);
  }

  public ASTPrograma(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cb4c1a62c896c40eaf9f36454e7492e8 (do not edit this line) */
