/* Generated By:JJTree: Do not edit this line. ASTPrograma.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPrograma extends SimpleNode {
  public ASTPrograma(int id) {
    super(id);
  }

  public ASTPrograma(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3d65238873b151f32e8b188ad122e4c1 (do not edit this line) */
