/* Generated By:JJTree: Do not edit this line. ASTRbrace.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRbrace extends SimpleNode {
  public ASTRbrace(int id) {
    super(id);
  }

  public ASTRbrace(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=247feafc5eed64e675429e3b6c1c1f66 (do not edit this line) */
