/* Generated By:JJTree: Do not edit this line. ASTRparen.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRparen extends SimpleNode {
  public ASTRparen(int id) {
    super(id);
  }

  public ASTRparen(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dc26218e58d8d80971688beaf031d843 (do not edit this line) */
