/* Generated By:JJTree: Do not edit this line. ASTRparen.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRparen extends SimpleNode {
  public ASTRparen(int id) {
    super(id);
  }

  public ASTRparen(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8c4931e88a4e88d6c4b7c33771693c31 (do not edit this line) */
