/* Generated By:JJTree: Do not edit this line. ASTSentenciaAsignacion.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSentenciaAsignacion extends SimpleNode {
  public ASTSentenciaAsignacion(int id) {
    super(id);
  }

  public ASTSentenciaAsignacion(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d086ee228bfd321a749ac2190e872d66 (do not edit this line) */
