/* Generated By:JJTree: Do not edit this line. ASTSentenciaWhile.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSentenciaWhile extends SimpleNode {
  public ASTSentenciaWhile(int id) {
    super(id);
  }

  public ASTSentenciaWhile(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=283f274124624959960b6388db02f3cc (do not edit this line) */
