/* Generated By:JJTree: Do not edit this line. ASTSentenciaReturn.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSentenciaReturn extends SimpleNode {
  public ASTSentenciaReturn(int id) {
    super(id);
  }

  public ASTSentenciaReturn(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7a7982705b7c382c44e2452d0d5fc795 (do not edit this line) */
