/* Generated By:JJTree: Do not edit this line. ASTSentenciaDo.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSentenciaDo extends SimpleNode {
  public ASTSentenciaDo(int id) {
    super(id);
  }

  public ASTSentenciaDo(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=436e12a502b65c70c7bb3925d4789a40 (do not edit this line) */
