/* Generated By:JJTree: Do not edit this line. ASTSentenciaFor.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSentenciaFor extends SimpleNode {
  public ASTSentenciaFor(int id) {
    super(id);
  }

  public ASTSentenciaFor(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1b5081aaa8750f8417aba3526b8ed6b4 (do not edit this line) */
