/* Generated By:JJTree: Do not edit this line. ASTSino.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSino extends SimpleNode {
  public ASTSino(int id) {
    super(id);
  }

  public ASTSino(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=54d0f49f8beb2a16281a426e7e6dbed8 (do not edit this line) */
