/* Generated By:JJTree: Do not edit this line. ASTSentenciaWrite.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSentenciaWrite extends SimpleNode {
  public ASTSentenciaWrite(int id) {
    super(id);
  }

  public ASTSentenciaWrite(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4c329abccb8a62d5542f1e2d448bafd0 (do not edit this line) */
