/* Generated By:JJTree: Do not edit this line. ASTSentenciaRead.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSentenciaRead extends SimpleNode {
  public ASTSentenciaRead(int id) {
    super(id);
  }

  public ASTSentenciaRead(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=db0fbfd0795a62cb7a42e2b1e5975c65 (do not edit this line) */
