/* Generated By:JJTree: Do not edit this line. ASTSentenciaRead.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSentenciaRead extends SimpleNode {
  public ASTSentenciaRead(int id) {
    super(id);
  }

  public ASTSentenciaRead(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d0d8bc8d352db9f76c7db9040699bef5 (do not edit this line) */
