/* Generated By:JJTree: Do not edit this line. ASTSentencias.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSentencias extends SimpleNode {
  public ASTSentencias(int id) {
    super(id);
  }

  public ASTSentencias(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=67a3455cc3fe85353847990a5a91ad24 (do not edit this line) */
