/* Generated By:JJTree: Do not edit this line. ASTSentenciaAsignacion.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSentenciaAsignacion extends SimpleNode {
  public ASTSentenciaAsignacion(int id) {
    super(id);
  }

  public ASTSentenciaAsignacion(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b7775640ab533686f86202f0ff4e3f66 (do not edit this line) */
