/* Generated By:JJTree: Do not edit this line. ASTSentenciaFor.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSentenciaFor extends SimpleNode {
  public ASTSentenciaFor(int id) {
    super(id);
  }

  public ASTSentenciaFor(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4f89f1104f1ae2880253283d391080b9 (do not edit this line) */
