/* Generated By:JJTree: Do not edit this line. ASTSino.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSino extends SimpleNode {
  public ASTSino(int id) {
    super(id);
  }

  public ASTSino(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b38f1dd7dffeaf3170794c478efdeca1 (do not edit this line) */
