/* Generated By:JJTree: Do not edit this line. ASTSentenciaIf.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSentenciaIf extends SimpleNode {
  public ASTSentenciaIf(int id) {
    super(id);
  }

  public ASTSentenciaIf(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a95c0be4fc8fd1530389a3728d89499f (do not edit this line) */
