/* Generated By:JJTree: Do not edit this line. ASTSemicolon.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSemicolon extends SimpleNode {
  public ASTSemicolon(int id) {
    super(id);
  }

  public ASTSemicolon(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8a566650ec49dd19849923aa9b25a468 (do not edit this line) */
