/* Generated By:JJTree: Do not edit this line. ASTSentenciaIf.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSentenciaIf extends SimpleNode {
  public ASTSentenciaIf(int id) {
    super(id);
  }

  public ASTSentenciaIf(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7e2cacf275824a0cf43f6de1060e6c9b (do not edit this line) */
