/* Generated By:JJTree: Do not edit this line. ASTSentenciaSwitch.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSentenciaSwitch extends SimpleNode {
  public ASTSentenciaSwitch(int id) {
    super(id);
  }

  public ASTSentenciaSwitch(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6f8badb1d83628564a821838a575c68c (do not edit this line) */
