/* Generated By:JJTree: Do not edit this line. ASTSentenciaDo.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSentenciaDo extends SimpleNode {
  public ASTSentenciaDo(int id) {
    super(id);
  }

  public ASTSentenciaDo(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8151a5b22db622f3d5aa7360123d18f9 (do not edit this line) */
