/* Generated By:JJTree: Do not edit this line. ASTTipoAsignar.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTipoAsignar extends SimpleNode {
  public ASTTipoAsignar(int id) {
    super(id);
  }

  public ASTTipoAsignar(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=48d645622b66cb312f5423f4fad54b61 (do not edit this line) */
