/* Generated By:JJTree: Do not edit this line. ASTTipoDato.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTipoDato extends SimpleNode {
  public ASTTipoDato(int id) {
    super(id);
  }

  public ASTTipoDato(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c071eb3b31a6db2f918fe089cd65aed8 (do not edit this line) */
