/* Generated By:JJTree: Do not edit this line. ASTTipoDato.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTipoDato extends SimpleNode {
  public ASTTipoDato(int id) {
    super(id);
  }

  public ASTTipoDato(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9779b7ccff1309a5ac7b0b5c9d26295a (do not edit this line) */
