/* Generated By:JJTree: Do not edit this line. ASTTipoAsignar.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTipoAsignar extends SimpleNode {
  public ASTTipoAsignar(int id) {
    super(id);
  }

  public ASTTipoAsignar(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c6d26217ec71f8468286ac0bcc3e844d (do not edit this line) */
