/* Generated By:JJTree: Do not edit this line. ASTTiposAsignaciones.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTiposAsignaciones extends SimpleNode {
  public ASTTiposAsignaciones(int id) {
    super(id);
  }

  public ASTTiposAsignaciones(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=45fb5b810a1e84fd2aaf12e8355c36c7 (do not edit this line) */
