/* Generated By:JJTree: Do not edit this line. ASTTiposDatos.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTiposDatos extends SimpleNode {
  public ASTTiposDatos(int id) {
    super(id);
  }

  public ASTTiposDatos(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=adc7f77f0c0b34d48a94e36499159404 (do not edit this line) */
