/* Generated By:JJTree: Do not edit this line. ASTVoid.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVoid extends SimpleNode {
  public ASTVoid(int id) {
    super(id);
  }

  public ASTVoid(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d1a3dd5102c6c53805d991d831d25440 (do not edit this line) */
