/* Generated By:JJTree: Do not edit this line. ASTValor.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTValor extends SimpleNode {
  public ASTValor(int id) {
    super(id);
  }

  public ASTValor(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fe1603b35d097c71d3d21d07ed1efe35 (do not edit this line) */
