/* Generated By:JJTree: Do not edit this line. ASTVariablesLocales.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVariablesLocales extends SimpleNode {
  public ASTVariablesLocales(int id) {
    super(id);
  }

  public ASTVariablesLocales(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c7a45dd044347e29a4dbe9420d17a726 (do not edit this line) */
