/* Generated By:JJTree: Do not edit this line. ASTVariablesAsignacion.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVariablesAsignacion extends SimpleNode {
  public ASTVariablesAsignacion(int id) {
    super(id);
  }

  public ASTVariablesAsignacion(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=33a125179b0fa0626e1f0f658debc142 (do not edit this line) */
