/* Generated By:JJTree: Do not edit this line. ASTValor.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTValor extends SimpleNode {
  public ASTValor(int id) {
    super(id);
  }

  public ASTValor(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=04272ae602bb63255025b3a772166352 (do not edit this line) */
