/* Generated By:JJTree: Do not edit this line. ASTVS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVS extends SimpleNode {
  public ASTVS(int id) {
    super(id);
  }

  public ASTVS(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a90e756205faa294ba675476cae16215 (do not edit this line) */
