/* Generated By:JJTree: Do not edit this line. ASTVariablesLocales.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVariablesLocales extends SimpleNode {
  public ASTVariablesLocales(int id) {
    super(id);
  }

  public ASTVariablesLocales(comp p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=555d98cef0fd5914a7368195e1a79970 (do not edit this line) */
