/* Generated By:JavaCC: Do not edit this line. compTreeConstants.java Version 5.0 */
public interface compTreeConstants
{
  public int JJTPROGRAMA = 0;
  public int JJTBLOQUE = 1;
  public int JJTBLOQUEDEDEFINICIONES = 2;
  public int JJTFUNCION = 3;
  public int JJTBLOQUEVARIABLESGLOBALES = 4;
  public int JJTMAIN = 5;
  public int JJTVARIABLESLOCALES = 6;
  public int JJTASIGNACION = 7;
  public int JJTVOID = 8;
  public int JJTSENTENCIAIF = 9;
  public int JJTSINO = 10;
  public int JJTA = 11;
  public int JJTCOMPARACIONES = 12;
  public int JJTVALOR = 13;
  public int JJTEXPRESION = 14;
  public int JJTOPERADORES = 15;
  public int JJTOPARITMETICO = 16;
  public int JJTTIPODATO = 17;
  public int JJTSENTENCIAFOR = 18;
  public int JJTDECLARACIONUNAVARIABLE = 19;
  public int JJTSENTENCIADO = 20;
  public int JJTSENTENCIAWHILE = 21;
  public int JJTSENTENCIAASIGNACION = 22;
  public int JJTTIPOASIGNAR = 23;
  public int JJTSENTENCIAWRITE = 24;
  public int JJTSENTENCIAREAD = 25;
  public int JJTRETURN = 26;
  public int JJTSENTENCIASWITCH = 27;
  public int JJTINT = 28;
  public int JJTDEC = 29;
  public int JJTCHR = 30;
  public int JJTIDENTIFIER = 31;
  public int JJTNUMBER = 32;
  public int JJTDECIMAL = 33;
  public int JJTCARAC = 34;
  public int JJTCADENA = 35;
  public int JJTBREAK = 36;
  public int JJTCOMMA = 37;
  public int JJTRPAREN = 38;
  public int JJTLPAREN = 39;
  public int JJTLBRACE = 40;
  public int JJTRBRACE = 41;
  public int JJTSEMICOLON = 42;
  public int JJTDOUBLEPOINT = 43;
  public int JJTOPBITS = 44;
  public int JJTERROR_SKIPTO = 45;


  public String[] jjtNodeName = {
    "Programa",
    "Bloque",
    "BloqueDeDefiniciones",
    "Funcion",
    "BloqueVariablesGlobales",
    "Main",
    "VariablesLocales",
    "Asignacion",
    "void",
    "SentenciaIf",
    "Sino",
    "A",
    "Comparaciones",
    "Valor",
    "Expresion",
    "Operadores",
    "OpAritmetico",
    "TipoDato",
    "SentenciaFor",
    "DeclaracionUnaVariable",
    "SentenciaDo",
    "SentenciaWhile",
    "SentenciaAsignacion",
    "TipoAsignar",
    "SentenciaWrite",
    "SentenciaRead",
    "Return",
    "SentenciaSwitch",
    "Int",
    "Dec",
    "Chr",
    "Identifier",
    "Number",
    "Decimal",
    "CARAC",
    "Cadena",
    "Break",
    "Comma",
    "Rparen",
    "Lparen",
    "Lbrace",
    "Rbrace",
    "Semicolon",
    "DoublePoint",
    "OpBits",
    "error_skipto",
  };
}
/* JavaCC - OriginalChecksum=2d50aace7016d278c19e41446f5cb15b (do not edit this line) */
