/* Generated By:JavaCC: Do not edit this line. compTreeConstants.java Version 6.0_1 */
public interface compTreeConstants
{
  public int JJTPROGRAMA = 0;
  public int JJTVOID = 1;
  public int JJTFUNCION = 2;
  public int JJTVARIABLESGLOBALES = 3;
  public int JJTPRINCIPAL = 4;
  public int JJTVARIABLESLOCALES = 5;
  public int JJTVARIABLESASIGNACION = 6;
  public int JJTVS = 7;
  public int JJTSENTENCIAS = 8;
  public int JJTSENTENCIAIF = 9;
  public int JJTSINO = 10;
  public int JJTA = 11;
  public int JJTCOMPARACIONES = 12;
  public int JJTVALOR = 13;
  public int JJTEXPRESION = 14;
  public int JJTOPERADORES = 15;
  public int JJTOPARITMETICO = 16;
  public int JJTTIPOSDATOS = 17;
  public int JJTSENTENCIAFOR = 18;
  public int JJTDECLARACIONUNAVARIABLE = 19;
  public int JJTSENTENCIADO = 20;
  public int JJTSENTENCIAWHILE = 21;
  public int JJTSENTENCIAASIGNACION = 22;
  public int JJTTIPOSASIGNACIONES = 23;
  public int JJTSENTENCIAWRITE = 24;
  public int JJTSENTENCIAREAD = 25;
  public int JJTSENTENCIARETURN = 26;
  public int JJTSENTENCIASWITCH = 27;
  public int JJTOPBITS = 28;


  public String[] jjtNodeName = {
    "Programa",
    "void",
    "Funcion",
    "VariablesGlobales",
    "Principal",
    "VariablesLocales",
    "VariablesAsignacion",
    "VS",
    "Sentencias",
    "SentenciaIf",
    "Sino",
    "A",
    "Comparaciones",
    "Valor",
    "Expresion",
    "Operadores",
    "OpAritmetico",
    "TiposDatos",
    "SentenciaFor",
    "DeclaracionUnaVariable",
    "SentenciaDo",
    "SentenciaWhile",
    "SentenciaAsignacion",
    "TiposAsignaciones",
    "SentenciaWrite",
    "SentenciaRead",
    "SentenciaReturn",
    "SentenciaSwitch",
    "OpBits",
  };
}
/* JavaCC - OriginalChecksum=6939cd41b852cfa1cfd3d738013e3b1f (do not edit this line) */
