/* Generated By:JavaCC: Do not edit this line. compTreeConstants.java Version 6.0_1 */
public interface compTreeConstants
{
  public int JJTPROGRAMA = 0;
  public int JJTVOID = 1;
  public int JJTBLOQUEDEDEFINICIONES = 2;
  public int JJTFUNCION = 3;
  public int JJTBLOQUEVARIABLESGLOBALES = 4;
  public int JJTMAIN = 5;
  public int JJTASIGNACION = 6;
  public int JJTSENTENCIAIF = 7;
  public int JJTSINO = 8;
  public int JJTA = 9;
  public int JJTCOMPARACIONES = 10;
  public int JJTVALOR = 11;
  public int JJTEXPRESION = 12;
  public int JJTOPERADORES = 13;
  public int JJTOPARITMETICO = 14;
  public int JJTTIPODATO = 15;
  public int JJTSENTENCIAFOR = 16;
  public int JJTDECLARACIONUNAVARIABLE = 17;
  public int JJTSENTENCIADO = 18;
  public int JJTSENTENCIAWHILE = 19;
  public int JJTSENTENCIAASIGNACION = 20;
  public int JJTTIPOASIGNAR = 21;
  public int JJTSENTENCIAWRITE = 22;
  public int JJTSENTENCIAREAD = 23;
  public int JJTSENTENCIARETURN = 24;
  public int JJTSENTENCIASWITCH = 25;
  public int JJTINT = 26;
  public int JJTDEC = 27;
  public int JJTCHR = 28;
  public int JJTIDENTIFIER = 29;
  public int JJTNUMBER = 30;
  public int JJTDECIMAL = 31;
  public int JJTCARAC = 32;
  public int JJTCOMMA = 33;
  public int JJTRPAREN = 34;
  public int JJTLPAREN = 35;
  public int JJTLBRACE = 36;
  public int JJTRBRACE = 37;
  public int JJTOPBITS = 38;


  public String[] jjtNodeName = {
    "Programa",
    "void",
    "BloqueDeDefiniciones",
    "Funcion",
    "BloqueVariablesGlobales",
    "Main",
    "Asignacion",
    "SentenciaIf",
    "Sino",
    "A",
    "Comparaciones",
    "Valor",
    "Expresion",
    "Operadores",
    "OpAritmetico",
    "TipoDato",
    "SentenciaFor",
    "DeclaracionUnaVariable",
    "SentenciaDo",
    "SentenciaWhile",
    "SentenciaAsignacion",
    "TipoAsignar",
    "SentenciaWrite",
    "SentenciaRead",
    "SentenciaReturn",
    "SentenciaSwitch",
    "Int",
    "Dec",
    "Chr",
    "Identifier",
    "Number",
    "Decimal",
    "CARAC",
    "Comma",
    "Rparen",
    "Lparen",
    "Lbrace",
    "Rbrace",
    "OpBits",
  };
}
/* JavaCC - OriginalChecksum=832ea94a608bcdb55d416eb186acf545 (do not edit this line) */
